version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dependencies'
    schedule:
      interval: 'daily'
    assignees:
      - 'BGruenberg'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "@angular*"
        update-types: [
          "version-update:semver-minor",
          "version-update:semver-patch"
        ]
      - dependency-name: "@ng-bootstrap/ng-bootstrap"
        update-types: [
          "version-update:semver-minor",
          "version-update:semver-patch"
        ]
    groups:
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
      cypress:
        patterns:
          - "cypress"
          - "@cypress/schematics"

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
    assignees:
      - 'BGruenberg'
    cooldown:
      default-days: 7
    allow:
      - dependency-name: "@angular*"
      - dependency-name: "@ng-bootstrap/ng-bootstrap"
    ignore:
      - dependency-name: "@angular-devkit/architect"
        versions: [">=0.2200.0"]
    groups:
      angular-minor:
        patterns:
          - "@angular*"
          - "@ng-bootstrap/ng-bootstrap"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'dependencies'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Berlin

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'dependencies'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Europe/Berlin
