const fs = require('fs');
const packageJson = require('./package.json');

const imprint = `
  <h2>Herausgeber</h2>
  <h3>Firmenname</h3>
    <p>
      Firmenadresse
    </p>

    <p>
      Kontaktdaten
    </p>

  <h2>Rechtliche Hinweise</h2>
    <p>
      Hinweise
    </p>

  <h2>Realisierung</h2>
    <p>
      Design, Entwicklung
    </p>
    <p>
      Dataport<br>
      Anstalt öffentlichen Rechts<br>
      Altenholzer Straße 10-14<br>
      24161 Altenholz<br>
      Tel.: +49 (0)431 3295-0<br>
      Fax.: +49 (0)431 3295-0<br>
    </p>
    <p>
      E-Mail: <a href="mailto:dataportdabstimmbox@dataport.de">dataportdabstimmbox@dataport.de</a>
    </p>

  <h2>Inhalte</h2>
    <p>
      Für Vollständigkeit, Fehler redaktioneller und technischer Art, Auslassungen sowie die Richtigkeit der Eintragungen kann keine
      Haftung übernommen werden. Insbesondere kann keine Gewähr für die Vollständigkeit und Richtigkeit von Informationen übernommen
      werden, die über weiterführende Links erreicht werden.
    </p>
    <p>
      Anbieter dieser Links sind für die eigenen Inhalte, die sie zur Nutzung bereithalten, nach den allgemeinen Gesetzen
      verantwortlich. Von diesen eigenen Inhalten sind Querverweise auf die von anderen Anbietern bereitgehaltenen Inhalte zu
      unterscheiden.
    </p>

  <div>Stand 13. September 2022</div>
`;
const privacy = `<h2>privacy</h2>`;
const tos = `<h2>tos</h2>`;
const accessibility = `<h2>accessibility</h2>`;

function reformat(value) {
  if (value === undefined) {
    return value;
  }
  return `'${value}'`;
}

fs.readFile('./src/environments/environment.ts.tmpl', 'utf8', function (err, data) {
  if (err) {
    throw err;
  }

  if (process.env.DOCKER === 'true') {
    data = data
      .replace('@TITLE@', reformat('@TITLE@'))
      .replace('@LOCALE@', reformat('@LOCALE@'))
      .replace('@ADDRESSING@', reformat('@ADDRESSING@'))
      .replace('@API_URL@', reformat('@API_URL@'));
  } else {
    data = data
      .replace('@TITLE@', reformat(process.env.TITLE ? process.env.TITLE : ''))
      .replace('@LOCALE@', reformat(process.env.LOCALE ? process.env.LOCALE : 'de-DE'))
      .replace('@ADDRESSING@', reformat(process.env.ADDRESSING ? process.env.ADDRESSING : 'du'))
      .replace('@API_URL@', reformat(process.env.API_URL));
  }

  if (process.env.PRODUCTION === "true" || process.env.PRODUCTION === "false") {
    data = data
      .replace('@PRODUCTION@', process.env.PRODUCTION)
      .replace('@CONSOLE_LOGGING_OPTIONS@', `{momentDateTimeFormat: 'YYYY-MM-DD HH:mm:ss.SSS', logLevelThreshold: ${process.env.PRODUCTION ? 'LogLevel.WARN' : 'LogLevel.DEBUG'}}`);
  } else {
    data = data
      .replace('@PRODUCTION@', 'true')
      .replace('@CONSOLE_LOGGING_OPTIONS@', `{momentDateTimeFormat: 'YYYY-MM-DD HH:mm:ss.SSS', logLevelThreshold: LogLevel.WARN}`);
  }

  data = data
    .replace('@GENERATED_COMMENT_TS@', '// AUTO GENERATED - DO NOT EDIT THIS FILE')
    .replace('@VERSION@', reformat(process.env.VERSION ? process.env.VERSION : packageJson.version))
    .replace('@BUILD_DATE@', reformat(new Date().toISOString()))
    .replace('@SURVEY_LINK_ADMIN@', reformat(process.env.SURVEY_LINK_ADMIN ? process.env.SURVEY_LINK_ADMIN : undefined))
    .replace('@SURVEY_LINK_USER@', reformat(process.env.SURVEY_SURVEY_LINK_USER ? process.env.SURVEY_SURVEY_LINK_USER : undefined))
    .replace('@EMAIL@', reformat(process.env.EMAIL ? process.env.EMAIL : 'demo@example.com'))
    .replace('@CUSTOMER_ID@', reformat(process.env.CUSTOMER_ID ? process.env.CUSTOMER_ID : '80248A42-8FE2-4D4A-89DA-02E683511F76'))
    .replace('@IMPRINT@', process.env.IMPRINT ? process.env.IMPRINT : `\`${imprint}\``)
    .replace('@PRIVACY@', process.env.PRIVACY ? process.env.PRIVACY : `\`${privacy}\``)
    .replace('@TOS@', process.env.TOS ? process.env.TOS : `\`${tos}\``)
    .replace('@ACCESSIBILITY@', process.env.TOS ? process.env.ACCESSIBILITY : `\`${accessibility}\``)
    .replace('@API_REQUEST_TIMEOUT_IN_MS@', process.env.PRODUCTION === false ? '180000' : '20000')
    .replace('@API_MEDIA_TYPE@', reformat(process.env.API_MEDIA_TYPE ? process.env.API_MEDIA_TYPE : 'application/terminfinder.api-v1+json'));

  fs.writeFile('./src/environments/environment.ts', data, 'utf8', function (err) {
    if (err) {
      throw err;
    }
  });
});

fs.readFile('./src/index.html.tmpl', 'utf8', function (err, data) {
  if (err) {
    throw err;
  }

  data = data
    .replace('@TITLE@', process.env.TITLE);

  fs.writeFile('./src/index.html', data, 'utf8', function (err) {
    if (err) {
      throw err;
    }
  });
});
