// AUTO GENERATED - DO NOT EDIT THIS FILE
// Only edit the file with the extension *.tmpl

import { EnvConfig } from './env-config.interface';
import { LogLevel } from '../app/shared/services/logging/logLevel';

/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access */
// @ts-ignore
const env = window.__env ?? ({} as Partial<EnvConfig>);

export const environment: EnvConfig = {
  version: env.version,
  buildDateUtc: env.buildDateUtc,
  surveyLinkAdmin: env.surveyLinkAdmin,
  surveyLinkUser: env.surveyLinkUser,
  title: env.title,
  locale: env.locale,
  addressing: env.addressing,
  apiBaseUrl: env.apiBaseUrl,
  email: env.email,
  showReference: env.showReference,
  customerId: env.customerId,
  imprint: env.imprint,
  privacy: env.privacy,
  termsOfService: env.termsOfService,
  accessibility: env.accessibility,
  apiRequestTimeoutInMs: env.apiRequestTimeoutInMs,
  consoleLoggingOptions: { momentDateTimeFormat: 'YYYY-MM-DD HH:mm:ss.SSS', logLevelThreshold: LogLevel.WARN },
  apiMediaType: 'application/terminfinder.api-v1+json',
  colors: env.colors
};
